### ISSUE TITLE
Particle flashDeviceAPI Call Error

### ISSUE THREAD

**Issue by bulletshot60** [spark/particle-api-js#12]
I am getting an error while attempting to flash a cpp file to my device.  The error received is:
```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:186:14)
    at Transform.Writable.write (_stream_writable.js:213:12)
    at FormData.ondata (stream.js:31:26)
    at emitOne (events.js:90:13)
    at FormData.emit (events.js:182:7)
    at FormData.CombinedStream.write (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:118:8)
    at FormData.CombinedStream._pipeNext (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:106:8)
    at FormData.CombinedStream._getNext (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.CombinedStream._getNext (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:79:10)
    at FormData.CombinedStream._pipeNext (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:107:8)
    at FormData.<anonymous> (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:91:10)
    at FormData.<anonymous> (/Users/ethanmcgee/git/clemson/das-provider/node_modules/superagent/node_modules/form-data/lib/form_data.js:201:5)
    at FormData.CombinedStream._getNext (/Users/ethanmcgee/git/clemson/das-provider/node_modules/combined-stream/lib/combined_stream.js:84:3)
    at emitNone (events.js:85:20)
    at DelayedStream.emit (events.js:179:7)
```

The code which generates the error is:

```
var fullCode = "<cpp code here>";
fs.writeFile("./" + deviceId + ".cpp", fullCode, function(err) {
    var ccPr = particle.compileCode({files: {"temp.cpp": "./" + deviceId + ".cpp"}, platformId: 6, auth: authToken});

    ccPr.then(function(data) {
        var flashPr = particle.flashDevice({
            deviceId: deviceId,
            files: {"temp.cpp": "./" + deviceId + ".cpp"},
            auth: authToken
        });
        flashPr.then(function (data) {
            //magic goes here
        }, function (err) {
            //something bad happened with flash
        });
    }, function(err) {
        //something bad happened with compile
    });
});
```

I am using the latest version of the API, 5.2.3.

**Comment by brycekahle** [comment]
I think I know what the error is. Can you try specifying `platformId` as `'6'`? If that fixes it, I will fix the library.

**Comment by bulletshot60** [comment]
```
var fdPr = particle.flashDevice({
    deviceId: device[0].deviceId,
    plaformId: '6',
    files: {"temp.cpp": "./" + device[0].deviceId + ".cpp"},
    auth: req.session.user.particleApiAuthToken
});
```
I tried it as both ```6``` and ```'6'``` with the same error message resulting.

**Comment by brycekahle** [comment]
Are you using this from `node` or the browser? I noticed you are using a relative file path too, so I would verify that is correct.

**Comment by bulletshot60** [comment]
I am doing this from node, and yes, the relative file path is correct.

-- 
Ethan McGee
Sent with Airmail

On March 21, 2016 at 2:15:33 PM, Bryce Kahle (notifications@github.com) wrote:

Are you using this from node or the browser? I noticed you are using a relative file path too, so I would verify that is correct.

**Comment by brycekahle** [comment]
Another note is that you can call only `flashDevice` if you want, and it will compile and flash.

**Comment by bulletshot60** [comment]
I noticed that from the documentation on the main site.  However, when I encountered the stream error with ```flashDevice``` I wrapped it in a compile thinking maybe ```flashDevice``` failed if there was a syntax error in the cpp.

**Comment by brycekahle** [comment]
I've definitely tested this from node and had success. Can you try using the absolute file path?

**Comment by brycekahle** [comment]
Oh, is `compileCode` succeeding but `flashDevice` is failing?

**Comment by bulletshot60** [comment]
Yes,

That is the issue that I am experiencing.  Compile works correctly, flash throws the streams error.

-- 
Ethan McGee
Sent with Airmail

On March 21, 2016 at 2:26:14 PM, Bryce Kahle (notifications@github.com) wrote:

Oh, is compileCode succeeding but flashDevice is failing?

**Comment by brycekahle** [comment]
Got it. I know the issue. New release forthcoming.

**Comment by bulletshot60** [comment]
Thank you much. Please let me know when to pull.

**Comment by brycekahle** [comment]
`5.2.4` just published

**Comment by bulletshot60** [comment]
Also, as an aside.

The documentation on docs.particle.io hasn't been updated to reflect changes to the JS API.  It states that compile and flash both take a list of files rather than an object.  Anyone that does some poking can find the discrepancy, just an FYI.

**Comment by brycekahle** [comment]
Thanks for the heads up on that.

**Comment by bulletshot60** [comment]
Does flash device queue the binary until the device turns on?  The API call returns true even though my device is definitely off.

**Comment by brycekahle** [comment]
Not at the moment. Are you using a Photon or Electron?

**Comment by bulletshot60** [comment]
Photon.

**Comment by bulletshot60** [comment]
Should I continue passing the platformId of 6?

**Comment by brycekahle** [comment]
For `flashDevice` it is not needed because you are passing the `deviceId`.

**Comment by bulletshot60** [comment]
Okay,  well in any case, ```flashDevice``` returning true even when the device is off is not problematic to my use case.  I just wasn't what I expected.

Thanks for your assistance.
